CREATE TABLE attendance_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    time_record_id BIGINT,
    request_type VARCHAR(20) NOT NULL,
    work_date DATE NOT NULL,
    requested_clock_in TIMESTAMP NOT NULL,
    requested_clock_out TIMESTAMP,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approver_id BIGINT,
    approved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_attendance_requests_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_attendance_requests_time_record FOREIGN KEY (time_record_id) REFERENCES time_records(id),
    CONSTRAINT fk_attendance_requests_approver FOREIGN KEY (approver_id) REFERENCES employees(id)
);

CREATE INDEX idx_attendance_requests_employee_status ON attendance_requests (employee_id, status);
CREATE INDEX idx_attendance_requests_approver_status ON attendance_requests (approver_id, status);
